# Play Get Server Address
- name: Get server ip 
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Get public_ip address of the ec2 instance 
    amazon.aws.ec2_instance_info:
      region: "{{ aws_region }}"
      filters:
        "tag:Name": "jenkins-server"
    register: ec2_info

# Play Prepare Jenkins Server - with all needed tools, Jenkins, Docker, Nodejs & npm
- name: Prepare server for Jenkins
  hosts: "{{ hostvars['localhost']['ec2_info'].instances[0].public_ip_address }}"
  become: yes
  tasks:
  - name: Include task for amazon-linux server
    include_tasks: ex4-host-amazon.yaml
    when: host_os == "amazon-linux"
  - name: Include task for ubuntu server
    include_tasks: ex4-host-ubuntu.yaml
    when: host_os == "ubuntu"

  # These work for both OS flavours
  - name: Check that nvm installed
    stat:
      path: ~/.nvm
    register: stat_result
  - name: Download nvm installer
    get_url: 
      url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh
      dest: ./install.sh
    when: not stat_result.stat.exists
  - name: Install nvm
    shell: bash install.sh
    when: not stat_result.stat.exists
  - name: Install node
    shell: "source /root/.nvm/nvm.sh && nvm install 8.0.0 && node --version" 
    args:
      executable: /bin/bash
    register: cmd_result
  - debug: msg={{ cmd_result }}

# Play Start Jenkins
- name: Start Jenkins
  hosts: "{{ hostvars['localhost']['ec2_info'].instances[0].public_ip_address }}"
  become: yes
  tasks:
  - name: Start Jenkins server
    service:
      name: jenkins
      state: started
  - name: Wait 10 seconds to check the Jenkins port
    pause:
      seconds: 10
  - name: Check that application started with netstat
    command: netstat -plnt
    register: app_status
  - debug: msg={{ app_status }} 
  - name: Print out Jenkins admin password
    slurp:
      src: /var/lib/jenkins/secrets/initialAdminPassword
    register: jenkins_pwd
  - debug: msg={{ jenkins_pwd['content'] }}