- name: Provision Ansible server
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Start an instance with a public IP address
    amazon.aws.ec2_instance:
      name: ansible-server
      key_name: ansible-control-server-key
      region: "{{ aws_region }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: t2.micro
      security_group: default
      image_id: "{{ ami_id }}"
      network:
        assign_public_ip: true
