- name: Wait until EC2 instance accepts SSH connections
  hosts: all
  gather_facts: no
  tasks:
    - name: Ensure ssh port is open
      wait_for:
        port: 22
        delay: 10
        timeout: 100
        search_regex: OpenSSH
        host: "{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}"
      vars:
        ansible_connection: local
        ansible_python_interpreter: /opt/homebrew/bin/python3

- name: Install Docker
  hosts: all
  become: yes
  become_user: root  # could be omitted since it is the default as soon as 'become' is enabled
  tasks:
    - name: Ensure Docker is installed
      yum:
        name: docker
        update_cache: yes
        state: present

- name: Install Docker Compose
  hosts: all
  become: yes
  tasks:
    - name: Get architecture of remote machine
      shell: echo `uname -s`-`uname -m`
      register: remote_arch
    - name: Download and install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-{{ remote_arch.stdout }}
        dest: /usr/local/bin/docker-compose
        mode: +x

- name: Start Docker
  hosts: all
  become: yes
  tasks:
    - name: Ensure Docker daemon is started
      systemd:
        name: docker
        state: started

- name: Add ec2-user to docker group
  hosts: all
  become: yes
  tasks:
    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes
    - name: Reset ssh connection to allow user changes to affect 'current login user'
      meta: reset_connection

- name: Install pip3
  hosts: all
  become: yes
  tasks:
    - name: Ensure pip3 is installed
      yum:
        name: python3-pip
        update_cache: yes
        state: present

- name: Install required Python modules
  hosts: all
  tasks:
    - name: Install Python modules 'docker' and 'docker-compose'
      pip:
        name:
          - docker
          - docker-compose

- name: Start Docker containers
  hosts: all
  # use a variables file holding the password for Docker login
  vars_files:
    - project-vars
  tasks:
    - name: Copy docker-compose.yaml
      copy:
        src: ../docker-compose.yaml
        dest: /home/ec2-user/docker-compose.yaml
    - name: Make sure a Docker login against the private registry on Docker Hub is established
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1  # could be omitted, as Docker-Hub is the default registry if nothing is specified
        username: fsiegrist
        password: "{{ docker_password }}"
        state: present
    - name: Start containers from docker-compose file
      community.docker.docker_compose:
        project_src: /home/ec2-user
        state: present
