- name: Deploy application to k8s in new namespace
  hosts: localhost
  tasks:
    - name: Create a k8s namespace
      kubernetes.core.k8s:
        kubeconfig: ~/.kube/config
        api_version: v1
        kind: Namespace
        name: ns-myapp
        state: present
    - name: Deploy nginx application
      kubernetes.core.k8s:
        src: ../k8s/nginx.yaml
        state: present
        kubeconfig: ~/.kube/config
        namespace: ns-myapp