- name: Install Docker and Docker Compose. Start Docker. Install pip3.
  hosts: aws_ec2
  become: yes
  tasks:
    - name: Ensure Docker is installed
      yum:
        name: docker
        update_cache: yes
        state: present
    - name: Get architecture of remote machine
      shell: echo `uname -s`-`uname -m`
      register: remote_arch
    - name: Download and install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-{{ remote_arch.stdout }}
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: Ensure Docker daemon is started
      systemd:
        name: docker
        state: started
    - name: Ensure pip3 is installed
      yum:
        name: python3-pip
        update_cache: yes
        state: present


- name: Create new Linux user fesi.
  hosts: aws_ec2
  become: yes
  tasks: 
    - name: Create new user fesi
      user:
        name: fesi
        groups: adm,docker
    - name: Create ansible tmp directory
      file:
        path: /home/fesi/.ansible/tmp
        state: directory
        mode: '0777'


- name: Start Docker containers (as user fesi).
  hosts: aws_ec2
  become: yes
  become_user: fesi
  vars_files:
    - project-vars
  tasks:
    - name: Install Python modules 'docker' and 'docker-compose'
      pip:
        name:
          - docker
          - docker-compose
    - name: Copy docker-compose.yaml
      copy:
        src: ../docker-compose.yaml
        dest: /home/fesi/docker-compose.yaml
    - name: Make sure a Docker login against the private registry on Docker Hub is established
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1
        username: fsiegrist
        password: "{{ docker_password }}"
        state: present
    - name: Start containers from docker-compose file
      community.docker.docker_compose:
        project_src: /home/fesi
        state: present