- name: Install node and npm
  hosts: 134.209.244.217
  tasks:
    - name: Update apt repo and cache
      apt:
        force_apt_get: yes
        update_cache: yes # Yes, true, True would also be possible
        cache_valid_time: 3600 # in seconds
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm

- name: Create new Linux user for the node app
  hosts: 134.209.244.217
  tasks:
    - name: Create Linux user
      user:
        name: demo
        comment: Demo user for deploying and running the node app
        group: admin

- name: Deploy nodejs application
  hosts: 134.209.244.217
  become: yes
  become_user: demo
  tasks:
    - name: Copy application tar file to the server and unpack it there
      unarchive:
        src: ../nodejs-app-1.0.0.tgz
        dest: /home/demo/
    - name: Install dependencies
      npm:
        path: /home/demo/package
    - name: Start application
      command: node /home/demo/package/app/server
      async: 1000
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status # register the return value of the module into a variable
    - debug: msg={{ app_status.stdout_lines }}
